-- 
-- Table `tl_antique_books`
-- 

CREATE TABLE `tl_antique_books` (
  `id` int(10) unsigned NOT NULL auto_increment,
  `tstamp` int(10) unsigned NOT NULL default '0',
  `zbior` varchar(64) NOT NULL default '',
  `nrInwent` smallint(5) unsigned NOT NULL default '0',
  `sygnatury` blob NULL,
  `oldSygnatury` varchar(255) NOT NULL default '',
  `height` varchar(64) NOT NULL default '',
  `width` varchar(64) NOT NULL default '',
  `eksl` varchar(64) NOT NULL default '',
  `supEksl` varchar(64) NOT NULL default '',
  `znakiWlas` varchar(64) NOT NULL default '',
  `drRekMarg` varchar(64) NOT NULL default '',
  `arkMat` varchar(64) NOT NULL default '',
  `zdobKraw` varchar(64) NOT NULL default '',
  `oblMat` varchar(64) NOT NULL default '',
  `oblKolor` varchar(64) NOT NULL default '',
  `okladziny` varchar(64) NOT NULL default '',
  `zdobOprawy` varchar(64) NOT NULL default '',
  `zapWiazOkucia` varchar(64) NOT NULL default '',
  `charZapWiaz` varchar(64) NOT NULL default '',
  `cover` smallint(5) unsigned NOT NULL default '0',
  `grzbiet` smallint(5) unsigned NOT NULL default '0',
  `konstru` smallint(5) unsigned NOT NULL default '0',
  `szycie` smallint(5) unsigned NOT NULL default '0',
  `kapitalki` smallint(5) unsigned NOT NULL default '0',
  `oblUbyt` smallint(5) unsigned NOT NULL default '0',
  `oblZnisz` smallint(5) unsigned NOT NULL default '0',
  `zapWiaz` smallint(5) unsigned NOT NULL default '0',
  `zabOpr` smallint(5) unsigned NOT NULL default '0',
  `blokKompl` smallint(5) unsigned NOT NULL default '0',
  `defBloku` smallint(5) unsigned NOT NULL default '0',
  `zMechBloku` smallint(5) unsigned NOT NULL default '0',
  `oslPapier` smallint(5) unsigned NOT NULL default '0',
  `kruPapier` smallint(5) unsigned NOT NULL default '0',
  `zacZal` smallint(5) unsigned NOT NULL default '0',
  `mikroOrg` smallint(5) unsigned NOT NULL default '0',
  `foxing` smallint(5) unsigned NOT NULL default '0',
  `owady` smallint(5) unsigned NOT NULL default '0',
  `sumaNum` smallint(5) unsigned NOT NULL default '0',
  `dezynfek` varchar(64) NOT NULL default '',
  `napKonserw` varchar(64) NOT NULL default '',
  `uwagi` mediumtext NULL,
  PRIMARY KEY  (`id`),
) ENGINE=MyISAM DEFAULT CHARSET=utf8;